var translationsEN = {
  BUTTON: {
    EDIT: "Edit",
    SAVE: "Save",
    RESET: "Reset",
    CANCEL: "Cancel",
    OK: "OK",
    TODAY: "Today",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatic",
    MANUAL: "Manual",
    EDIT: "Edit",
    HISTORIC: "Historic",
    SETTINGS: "Settings"
  },
  PAGE_TITLE: {
    AUTOMATIC: "Auto Mode",
    MANUAL: "Manual Mode",
    EDIT: "Edit Mode",
    HISTORIC: "Historic",
    SETTINGS: "Settings",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "BREAST FEEDING",
    BREAST_MANUAL_HEADER: "BREAST FEEDING",
    BREAST_LEFT_SIDE: "Left side",
    BREAST_RIGHT_SIDE: "Right side",
    BREAST_DURATION: "Duration",
    BREAST_RUN: "Run",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BABY'S BOTTLE",
    DIAPPER_HEADER: "DIAPPER",
    DIAPPER_PEE_LEVEL: "Pee Level",
    DIAPPER_POO_LEVEL: "Poo Level",
    BATH_HEADER: "BATH",
    BATH_MESSAGE_MALE: "Perfect: {{name}} is soft and clean",
    BATH_MESSAGE_FEMALE: "Perfect: {{name}} is soft and clean",
    MEDECINE_HEADER: "MEDECINE",
    MESSAGE_HEADER: "MESSAGE",
  },
  HISTORIC: {
    BREAK_HEADER: "PREVIOUS FEEDING :",
  },
  MENU: {},
  SETTINGS: {
    BABY_HEADER: "MY BABY",
    BABY_DEFAULT_NAME: "Baby",
  },
  ACRONYM: {
    DAY: "d",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "L",
    RIGHT: "R",
    WEIGHT: "kg",
    HEIGHT: "in",
  }
};

var translationsFR = {
  BUTTON: {
    EDIT: "Modifier",
    SAVE: "Enregistrer",
    RESET: "Réinitialiser",
    CANCEL: "Annuler",
    OK: "OK",
    TODAY: "Aujourd'hui",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatique",
    MANUAL: "Manuel",
    EDIT: "Edition",
    HISTORIC: "Historique",
    SETTINGS: "Réglages",
  },
  PAGE_TITLE: {
    AUTOMATIC: "Mode automatique",
    MANUAL: "Saisie manuelle",
    EDIT: "Mode Edition",
    HISTORIC: "Historique",
    SETTINGS: "Réglages",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "ALLAITEMENT",
    BREAST_MANUAL_HEADER: "ALLAITEMENT",
    BREAST_LEFT_SIDE: "Sein Gauche",
    BREAST_RIGHT_SIDE: "Sein Droit",
    BREAST_DURATION: "Durée",
    BREAST_RUN: "Démarrer",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BIBERON",
    DIAPPER_HEADER: "COUCHE",
    DIAPPER_PEE_LEVEL: "Niveau pipi",
    DIAPPER_POO_LEVEL: "Niveau selles",
    BATH_HEADER: "BAIN",
    BATH_MESSAGE_MALE: "Ca y est : {{name}} est doux et propre",
    BATH_MESSAGE_FEMALE: "Ca y est : {{name}} est douce et propre",
    MEDECINE_HEADER: "MEDICAMENT",
    MESSAGE_HEADER: "MESSAGE",
  },
  HISTORIC: {
    BREAK_HEADER: "REPAS PRECEDENT :",
  },
  MENU: {},
  SETTINGS: {
    BABY_HEADER: "INFORMATIONS BEBE",
    BABY_DEFAULT_NAME: "Bébé",
    BABY_SURNAME: "Prénom",
    BABY_NAME: "Nom",
    BIRTHDAY_MALE: "Né le ",
    BIRTHDAY_FEMALE: "Née le ",
    BABY_GENDER: "Sexe",
    BABY_BOY: "Garçon",
    BABY_GIRL: "Fille",
    BABY_WEIGHT: "Poid Naissance",
    BABY_HEIGHT: "Taille Naissance",
  },
  ACRONYM: {
    DAY: "j",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "G",
    RIGHT: "D",
    WEIGHT: "kg ",
    HEIGHT: "cm",
  }
}