/*var translations = {
  BUTTON: {
    EDIT: "",
    SAVE: "",
    RESET: "",
    CANCEL: "",
    OK: "",
    TODAY: "",
  },
  TAB_TITLE: {
    AUTOMATIC: "",
    MANUAL: "",
    EDIT: "",
    HISTORIC: "",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "",
    BREAST_MANUAL_HEADER: "",
    BREAST_LEFT_SIDE: "",
    BREAST_RIGHT_SIDE: "",
    BREAST_DURATION: "",
    BREAST_RUN:"",
    BREAST_PAUSE:"",
    BOTTLE_HEADER: "",
    DIAPPER_HEADER: "",
    DIAPPER_PEE_LEVEL: "",
    DIAPPER_POO_LEVEL: "",
    BATH_HEADER: "",
    BATH_MESSAGE: "",
    VITAMIN_HEADER: "",
    VITAMIN_MESSAGE: "",
    MESSAGE_HEADER: "",
  },
  HISTORIC: {
    BREAK_HEADER: "",
  },
  MENU: {},
  SETTING: {},
  ACCRONYM: {
    DAY: "",
    HOUR: "",
    MINUTE: "",
    SECOND: "",
    LEFT: "",
    RIGHT: "",
  }
};*/

var translationsEN = {
  BUTTON: {
    EDIT: "Edit",
    SAVE: "Save",
    RESET: "Reset",
    CANCEL: "Cancel",
    OK: "OK",
    TODAY: "Today",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatic",
    MANUAL: "Manual",
    EDIT: "Edit",
    HISTORIC: "Historic",
  },
  PAGE_TITLE: {
    AUTOMATIC: "Auto Mode",
    MANUAL: "Manual Mode",
    EDIT: "Edit Mode",
    HISTORIC: "Historic",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "BREAST FEEDING",
    BREAST_MANUAL_HEADER: "BREAST FEEDING",
    BREAST_LEFT_SIDE: "Left side",
    BREAST_RIGHT_SIDE: "Right side",
    BREAST_DURATION: "Duration",
    BREAST_RUN: "Run",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BABY'S BOTTLE",
    DIAPPER_HEADER: "DIAPPER",
    DIAPPER_PEE_LEVEL: "Pee Level",
    DIAPPER_POO_LEVEL: "Poo Level",
    BATH_HEADER: "BATH",
    BATH_MESSAGE: "{{babyName}} is soft and clean",
    VITAMIN_HEADER: "VITAMIN",
    VITAMIN_MESSAGE: " {{babyName}} is strong and safe",
    MESSAGE_HEADER: "MESSAGE",
  },
  HISTORIC: {
    BREAK_HEADER: "PREVIOUS FEEDING :",
  },
  MENU: {},
  SETTING: {},
  ACRONYM: {
    DAY: "d",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "L",
    RIGHT: "R",
  }
};

var translationsFR = {
  BUTTON: {
    EDIT: "Modifier",
    SAVE: "Enregistrer",
    RESET: "Réinitialiser",
    CANCEL: "Annuler",
    OK: "OK",
    TODAY: "Aujourd'hui",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatique",
    MANUAL: "Manuel",
    EDIT: "Edition",
    HISTORIC: "Historique",
  },
  PAGE_TITLE: {
    AUTOMATIC: "Mode automatique",
    MANUAL: "Saisie manuelle",
    EDIT: "Mode Edition",
    HISTORIC: "Historique",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "ALLAITEMENT",
    BREAST_MANUAL_HEADER: "ALLAITEMENT",
    BREAST_LEFT_SIDE: "Sein Gauche",
    BREAST_RIGHT_SIDE: "Sein Droit",
    BREAST_DURATION: "Durée",
    BREAST_RUN: "Démarrer",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BIBERON",
    DIAPPER_HEADER: "COUCHE",
    DIAPPER_PEE_LEVEL: "Niveau pipi",
    DIAPPER_POO_LEVEL: "Niveau selles",
    BATH_HEADER: "BAIN",
    BATH_MESSAGE: "{{babyName}} est doux et propre",
    VITAMIN_HEADER: "VITAMINE",
    VITAMIN_MESSAGE: " {{babyName}} est fort et protégé",
    MESSAGE_HEADER: "MESSAGE",
  },
  HISTORIC: {
    BREAK_HEADER: "REPAS PRECEDENT :",
  },
  MENU: {},
  SETTING: {},
  ACRONYM: {
    DAY: "j",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "G",
    RIGHT: "D",
  }
}