var translationsFR = {
  BUTTON: {
    EDIT: "Modif.",
    SAVE: "Enreg.",
    RESET: "Réinit.",
    CANCEL: "Annuler",
    OK: "OK",
    TODAY: "Aujourd'hui",
    IMPORT: "importer",
    EXPORT: "exporter",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatique",
    MANUAL: "Manuel",
    EDIT: "Edition",
    HISTORIC: "Historique",
    GRAPHIC: "Graphiques",
    SETTINGS: "Réglages",
  },
  PAGE_TITLE: {
    AUTOMATIC: "Mode automatique",
    MANUAL: "Saisie manuelle",
    EDIT: "Mode Edition",
    HISTORIC: "Historique",
    GRAPHIC: "Graphiques",
    MENU: "Réglages",
    BABY_INFOS: "Informations Bébé",
    BABIES_INFOS: "Informations Bébés",
    CONFIGURATION: "Configuration",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "ALLAITEMENT",
    BREAST_MANUAL_HEADER: "ALLAITEMENT",
    BREAST_LEFT_SIDE: "Sein Gauche",
    BREAST_RIGHT_SIDE: "Sein Droit",
    BREAST_DURATION: "Durée",
    BREAST_RUN: "Démarrer",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BIBERON",
    DIAPPER_HEADER: "COUCHE",
    DIAPPER_PEE_LEVEL: "Niveau pipi",
    DIAPPER_POO_LEVEL: "Niveau selles",
    BATH_HEADER: "BAIN",
    BATH_MESSAGE_MALE: "ça y est : {{name}} est doux et propre",
    BATH_MESSAGE_FEMALE: "ça y est : {{name}} est douce et propre",
    MEDECINE_HEADER: "MEDICAMENT",
    MEDECINE_VITAMIN: "Vitamines",
    MEDECINE_PARACETAMOL: "Paracetamol",
    MEDECINE_OTHER: "Autre :",
    MEASURE_HEADER: "MESURES",
    MEASURE_WEIGHT: "Poids",
    MEASURE_HEIGHT: "Taille",
    NOTE_HEADER: "NOTES",
    NOTE_PLACEHOLDER: "...",
  },
  HISTORIC: {
    BREAK_HEADER: "REPAS PRECEDENT :",
  },
  MENU: {
    BABY_INFOS: "Informations bébé",
    BABIES_INFOS: "Information bébés",
    CONFIGURATION: "Configuration",
    ACCOUNT: "Comptes   (pas encore disponible)",
  },
  SETTINGS: {
    BABY_HEADER: "MON BEBE",
    BABY_DEFAULT_NAME: "Bébé",
    BABY_FIRSTNAME: "Prénom",
    BABY_NAME: "Nom",
    BIRTHDAY_MALE: "Né le ",
    BIRTHDAY_FEMALE: "Née le ",
    BABY_GENDER: "Sexe",
    BABY_BOY: "Garçon",
    BABY_GIRL: "Fille",
    BABY_WEIGHT: "Poids Naissance",
    BABY_HEIGHT: "Taille Naissance",
    AUTO_MAN_HEADER: "MODE AUTOMATIQUE ET MANUEL",
    DISPLAY_HEADER: "AFFICHAGE CHAMPS",
    AUTO_MAN_INSTRUCTIONS: "Selectionner les informations à saisir et à afficher",
    GENERAL_HEADER: "GENERAL",
    GENERAL_LANGUAGE: "LANGUE",
    GENERAL_LANGUAGE_FRENCH: "Français",
    GENERAL_LANGUAGE_ENGLISH: "Anglais",
    GENERAL_UNITS: "UNITES",
    GENERAL_UNITS_STD: "Kg/mL",
    GENERAL_UNITS_ENG: "Oz/fl oz",
    GENERAL_NIGHT_LUMINOSITY: "ECLAIRAGE NUIT",
  },
  GRAPH: {
    WEIGHT_FIRST_MONTH: "1er Mois de {{name}}",
    WEIGHT_TITLE: "poids (kg)",
    BREAST_FEEDING_HEADER: "Tétés",
    BREAST_NUMBER_TITLE: "nombre par jour",
    BREAST_SUM_TITLE: "durée totale par jour (mn)",
    BREAST_SUM_CHOICE: "durée totale",
    BREAST_AVG_TITLE: "durée moyenne par jour (mn)",
    BREAST_AVG_CHOICE: "durée moyenne",
    BOTTLE_NUMBER_TITLE: "nombre par jour",
    BOTTLE_SUM_TITLE: "quantité totale par jour (ml)",
    BOTTLE_SUM_CHOICE: "quantité totale",
    BOTTLE_AVG_TITLE: "quantité moyenne par jour (ml)",
    BOTTLE_AVG_CHOICE: "quantité moyenne",
    DURATION_CHOICE: "Période ",
    DURATION_1_WEEK: "1 semaine",
    DURATION_2_WEEKS: "2 semaines",
    DURATION_1_MONTH: "4 semaines",
    DURATION_TO_DAY: "Jusqu'à",
    TODAY_TEXT: "aujourd'hui",
  },
  POPUP: {
    DATEPICKER_TITLE: "Selectionnez une date",
    TITLE_PICTURE_MENU: "GESTIONNAIRE PHOTO",
    OPEN_CAMERA: "Prendre une photo",
    OPEN_GALLERY: "Choisir dans gallerie",
    DELETE_PICTURE: "Effacer photo courante",
    CANCEL: "Annuler"
  },
  ACRONYM: {
    DAY: "j",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "G",
    RIGHT: "D",
    WEIGHT: "kg ",
    HEIGHT: "cm",
  },
  WEEK: {
    MONDAY: "Lundi",
    TUESDAY: "Mardi",
    WEDNESDAY: "Mercredi",
    THURSDAY: "Jeudi",
    FRIDAY: "Vendredi",
    SATURDAY: "Samedi",
    SUNDAY: "Dimanche",
  },
  MONTH: {
    JANUARY: "Janvier",
    FEBRUARY: "Fevrier",
    MARCH: "Mars",
    APRIL: "Avril",
    MAY: "Mai",
    JUNE: "Juin",
    JULY: "Juillet",
    AUGUST: "Aout",
    SEPTEMBER: "Septembre",
    OCTOBER: "Octobre",
    NOVEMBER: "Novembre",
    DECEMBER: "Decembre",
  }
}