var translationsEN = {
  BUTTON: {
    EDIT: "Edit",
    SAVE: "Save",
    RESET: "Reset",
    CANCEL: "Cancel",
    OK: "OK",
    TODAY: "Today",
  },
  TAB_TITLE: {
    AUTOMATIC: "Automatic",
    MANUAL: "Manual",
    EDIT: "Edit",
    HISTORIC: "Historic",
    GRAPHIC: "Charts",
    SETTINGS: "Settings"
  },
  PAGE_TITLE: {
    AUTOMATIC: "Auto Mode",
    MANUAL: "Manual Mode",
    EDIT: "Edit Mode",
    HISTORIC: "Historic",
    GRAPHIC: "Charts",
    MENU: "Settings",
    BABY_INFOS: "Baby Information",
    BABIES_INFOS: "Baby Information",
    CONFIGURATION: "Configuration",
  },
  INPUT: {
    BREAST_CHRONO_HEADER: "BREAST FEEDING",
    BREAST_MANUAL_HEADER: "BREAST FEEDING",
    BREAST_LEFT_SIDE: "Left side",
    BREAST_RIGHT_SIDE: "Right side",
    BREAST_DURATION: "Duration",
    BREAST_RUN: "Run",
    BREAST_PAUSE: "Pause",
    BOTTLE_HEADER: "BABY'S BOTTLE",
    DIAPPER_HEADER: "DIAPPER",
    DIAPPER_PEE_LEVEL: "Pee Level",
    DIAPPER_POO_LEVEL: "Poo Level",
    BATH_HEADER: "BATH",
    BATH_MESSAGE_MALE: "Perfect: {{name}} is soft and clean",
    BATH_MESSAGE_FEMALE: "Perfect: {{name}} is soft and clean",
    MEDECINE_HEADER: "MEDECINE",
    MEDECINE_VITAMIN: "Vitamin",
    MEDECINE_PARACETAMOL: "Paracetamol",
    MEDECINE_OTHER: "Other :",
    MEASURE_HEADER: "MEASURES",
    MEASURE_WEIGHT: "Weight",
    MEASURE_HEIGHT: "Height",
    NOTE_HEADER: "NOTES",
    NOTE_PLACEHOLDER: "...",
  },
  HISTORIC: {
    BREAK_HEADER: "PREVIOUS FEEDING :",
  },
  MENU: {
    BABY_INFOS: "Baby Information",
    BABIES_INFOS: "Baby Information",
    CONFIGURATION: "Configuration",
    ACCOUNT: "Account   (not yet available)",
  },
  SETTINGS: {
    BABY_HEADER: "MY BABY",
    BABY_DEFAULT_NAME: "Baby",
    BABY_FIRSTNAME: "First Name",
    BABY_NAME: "Name",
    BIRTHDAY_MALE: "Birthday",
    BIRTHDAY_FEMALE: "Birthday",
    BABY_GENDER: "Gender",
    BABY_BOY: "Boy",
    BABY_GIRL: "Girl",
    BABY_WEIGHT: "Weight",
    BABY_HEIGHT: "Height",
    AUTO_MAN_HEADER: "AUTOMATIC / MANUAL MODE",
    DISPLAY_HEADER: "DISPLAY",
    AUTO_MAN_INSTRUCTIONS: "Choose which field to use :",
    GENERAL_HEADER: "GENERAL",
    GENERAL_LANGUAGE: "LANGUAGE",
    GENERAL_LANGUAGE_FRENCH: "French",
    GENERAL_LANGUAGE_ENGLISH: "English",
    GENERAL_UNITS: "UNITS",
    GENERAL_UNITS_STD: "Kg/mL",
    GENERAL_UNITS_ENG: "Oz/fl oz",
    GENERAL_NIGHT_LUMINOSITY: "NIGTH INTENSITY",
  },
  POPUP: {
    DATEPICKER_TITLE: "Pick a Date",
    TITLE_PICTURE_MENU: "PICTURE MANAGER",
    OPEN_CAMERA: "Take a picture",
    OPEN_GALLERY: "Open gallery",
    DELETE_PICTURE: "Delete current picture",
    CANCEL: "Cancel"
  },
  ACRONYM: {
    DAY: "d",
    HOUR: "h",
    MINUTE: "mn",
    SECOND: "s",
    LEFT: "L",
    RIGHT: "R",
    WEIGHT: "kg",
    HEIGHT: "in",
  },
  WEEK: {
    MONDAY: "Monday",
    TUESDAY: "Tuesday",
    WEDNESDAY: "Wednesday",
    THURSDAY: "Thursday",
    FRIDAY: "Friday",
    SATURDAY: "Saturday",
    SUNDAY: "Sunday",
  },
  MONTH: {
    JANUARY: "January",
    FEBRUARY: "February",
    MARCH: "March",
    APRIL: "April",
    MAY: "May",
    JUNE: "June",
    JULY: "July",
    AUGUST: "August",
    SEPTEMBER: "Septembrer",
    OCTOBER: "October",
    NOVEMBER: "November",
    DECEMBER: "December",
  }
};